### ISSUE TITLE
유저 페이지 템플릿, 사이드 바 UI 구현

### ISSUE THREAD

**Issue by chanyDev** [showMeTheMoneyPrac/FE_repo#10]
## Description
유저 페이지 내 정보, 구매 목록 공통 템플릿 레이아웃 구현 및 사이드 바 UI 완성

## Todo
- [x] 유저 페이지 레이아웃 템플릿 UI 구현
- [x] 사이드 바 UI 완성
- [x] 사이드 바 네비게이션 url에 따른 동적 스타일링 구현
