### ISSUE TITLE
로그인 회원 가입 수정

### ISSUE THREAD

**Issue by jungks9351** [showMeTheMoneyPrac/FE_repo#29]
## Description
로그인 회원 가입 예외처리 구현
로그인 회원가입 UI 수정
API 변수명 변경
로그인 상태 전역상태 관리

## Todo
- [x] 로그인 예외처리 구현
- [x] 회원가입 예외처리 구현
- [x] 로그인 회원가입 UI 수정
- [x] API 변수명 변경
- [x] 로그인 상태 전역상태 관리
