### ISSUE TITLE
메인페이지 UI 구현

### ISSUE THREAD

**Issue by jungks9351** [showMeTheMoneyPrac/FE_repo#35]
## Description
메인페이지 UI 구현

## Todo
- [x] 상품 리스트 UI 구현
- [x] 상품 카테고리 nav UI 구현
- [x] 상품 카테고리별 라우팅 처리
