### ISSUE TITLE
헤더 테스트 코드 작성

### ISSUE THREAD

**Issue by jungks9351** [showMeTheMoneyPrac/FE_repo#4]
## Description
공통 헤더 테스트 코드 작성

## Todo
- [x] 헤더 렌더링 테스트 코드 작성
- [x] 헤더 라우팅 테스트 코드 작성
- [x] 헤더 검색바 렌더링 코드 작성
