### ISSUE TITLE
상품 상세페이지 레이아웃 구현 및 장바구니 담기 구현

### ISSUE THREAD

**Issue by jungks9351** [showMeTheMoneyPrac/FE_repo#55]
## Description
상품 상세페이지 레이아웃 구현
장바구니 담기 구현
상품 상세페이지 라우팅 구현

## Todo
- [x] 상품 상세페이지 라우팅 구현
- [x] 상품 상세페이지 레이아웃 구현
- [x] 장바구니 담기 구현
